Repository BlueBrain/nexus-sdk-js, pull requests merged in 2019-01, with the labels that each got.

#41 Finish orgs
  nexus-sdk-js/README.md
  nexus-sdk-js/package-lock.json
  nexus-sdk-js/src/Organization/__tests__/Oragnization.spec.ts
  nexus-sdk-js/src/Organization/index.ts
  nexus-sdk-js/src/Organization/utils.ts
  nexus-sdk-js/src/__tests__/__snapshots__/Nexus.spec.ts.snap
  nexus-sdk-js/src/utils/http.ts
Labels: nexus-sdk-js, review

#43 add tests for aggregation
  nexus-sdk-js/src/__mocks__/helpers.ts
  nexus-sdk-js/src/views/ElasticSearchView/__tests__/ElasticSearchView.spec.ts
  nexus-sdk-js/src/views/ElasticSearchView/index.ts
Labels: review

#45 bump
  nexus-sdk-js/package.json
Labels: review

#46 Distinguish between Single and Aggregate ES views
  nexus-sdk-js/src/Organization/__tests__/Organization.spec.ts
  nexus-sdk-js/src/views/ElasticSearchView/__tests__/ElasticSearchView.spec.ts
  nexus-sdk-js/src/views/ElasticSearchView/index.ts
Labels: nexus-sdk-js, nexus-web, review

#48 Reject none 2xx
  nexus-sdk-js/package-lock.json
  nexus-sdk-js/package.json
  nexus-sdk-js/src/Organization/__tests__/Organization.spec.ts
  nexus-sdk-js/src/Organization/utils.ts
  nexus-sdk-js/src/Project/__tests__/Project.spec.ts
  nexus-sdk-js/src/Project/utils.ts
  nexus-sdk-js/src/utils/__tests__/http.spec.ts
  nexus-sdk-js/src/utils/http.ts
  nexus-sdk-js/src/views/ElasticSearchView/__tests__/ElasticSearchView.spec.ts
Labels: review

#49 fix fetching all resources issue
  nexus-sdk-js/package-lock.json
  nexus-sdk-js/package.json
  nexus-sdk-js/src/Project/index.ts
  nexus-sdk-js/src/Resource/index.ts
  nexus-sdk-js/src/Resource/utils.ts
Labels: review

#50 publishing 0.1.7 as 0.1.6 seems to have crashed somehow
  nexus-sdk-js/package-lock.json
  nexus-sdk-js/package.json
Labels: review

#47 Raw ES query and list all views
  nexus-sdk-js/README.md
  nexus-sdk-js/package-lock.json
  nexus-sdk-js/package.json
  nexus-sdk-js/src/Project/__tests__/Project.spec.ts
  nexus-sdk-js/src/Project/index.ts
  nexus-sdk-js/src/View/ElasticSearchView/__tests__/ElasticSearchView.spec.ts
  nexus-sdk-js/src/View/ElasticSearchView/index.ts
  nexus-sdk-js/src/View/SparqlView/__tests__/SparqlView.spec.ts
  nexus-sdk-js/src/View/SparqlView/exceptions.ts
  nexus-sdk-js/src/View/SparqlView/index.ts
  nexus-sdk-js/src/View/index.ts
  nexus-sdk-js/src/View/utils.ts
  nexus-sdk-js/src/__mocks__/helpers.ts
  nexus-sdk-js/src/index.ts
  nexus-sdk-js/src/views/index.ts
  nexus-sdk-js/tsconfig.json
Labels: nexus-sdk-js, nexus-web, review

#51 catching excpetions, returning undefined and filtering out
  nexus-sdk-js/src/Organization/utils.ts
  nexus-sdk-js/src/Project/utils.ts
  nexus-sdk-js/src/Resource/utils.ts
Labels: review

#53 only name is required
  nexus-sdk-js/package.json
  nexus-sdk-js/src/Project/__tests__/Project.spec.ts
  nexus-sdk-js/src/Project/types.ts
Labels: review

#52 no TS specific export
  nexus-sdk-js/src/View/index.ts
Labels: review

#54 Add a json serializer method to Resource
  nexus-sdk-js/src/Resource/index.ts
Labels: review

#55 362 refactor v1 final
  nexus-sdk-js/package-lock.json
  nexus-sdk-js/package.json
  nexus-sdk-js/src/Nexus.ts
  nexus-sdk-js/src/Organization/__tests__/Organization.spec.ts
  nexus-sdk-js/src/Organization/index.ts
  nexus-sdk-js/src/Organization/types.ts
  nexus-sdk-js/src/Organization/utils.ts
  nexus-sdk-js/src/Project/__tests__/Project.spec.ts
  nexus-sdk-js/src/Project/index.ts
  nexus-sdk-js/src/Project/types.ts
  nexus-sdk-js/src/Project/utils.ts
  nexus-sdk-js/src/Resource/__tests__/Resource.spec.ts
  nexus-sdk-js/src/Resource/index.ts
  nexus-sdk-js/src/Resource/types.ts
  nexus-sdk-js/src/Resource/utils.ts
  nexus-sdk-js/src/View/SparqlView/__tests__/SparqlView.spec.ts
  nexus-sdk-js/src/View/utils.ts
  nexus-sdk-js/src/__mocks__/helpers.ts
  nexus-sdk-js/src/__tests__/Nexus.spec.ts
  nexus-sdk-js/src/utils/http.ts
  nexus-sdk-js/src/utils/types.ts
Labels: review

#56 Realms implementation
  nexus-sdk-js/src/Realm/__mocks__/mockReponses.ts
  nexus-sdk-js/src/Realm/__tests__/Realm.spec.ts
  nexus-sdk-js/src/Realm/index.ts
  nexus-sdk-js/src/Realm/types.ts
  nexus-sdk-js/src/Realm/utils.ts
  nexus-sdk-js/src/index.ts
  nexus-sdk-js/src/utils/types.ts
Labels: review

#59 Add HTTP PATCH util function
  nexus-sdk-js/src/utils/http.ts
Labels: review

#60 Refactor/elasticsearch id name
  nexus-sdk-js/package-lock.json
  nexus-sdk-js/package.json
  nexus-sdk-js/src/View/utils.ts
Labels: review

#61 update test
  nexus-sdk-js/src/__mocks__/helpers.ts
Labels: review

#62 Paginated orgs and project
  nexus-sdk-js/src/Nexus.ts
  nexus-sdk-js/src/Organization/__tests__/Organization.spec.ts
  nexus-sdk-js/src/Organization/index.ts
  nexus-sdk-js/src/Organization/types.ts
  nexus-sdk-js/src/Organization/utils.ts
  nexus-sdk-js/src/Project/index.ts
  nexus-sdk-js/src/Project/types.ts
  nexus-sdk-js/src/Project/utils.ts
  nexus-sdk-js/src/Realm/utils.ts
  nexus-sdk-js/src/Resource/__tests__/Resource.spec.ts
  nexus-sdk-js/src/Resource/index.ts
  nexus-sdk-js/src/Resource/types.ts
  nexus-sdk-js/src/Resource/utils.ts
  nexus-sdk-js/src/View/ElasticSearchView/index.ts
  nexus-sdk-js/src/View/ElasticSearchView/types.ts
  nexus-sdk-js/src/View/ElasticSearchView/utils.ts
  nexus-sdk-js/src/View/SparqlView/index.ts
  nexus-sdk-js/src/View/SparqlView/types.ts
  nexus-sdk-js/src/View/utils.ts
  nexus-sdk-js/src/__mocks__/helpers.ts
  nexus-sdk-js/src/__tests__/Nexus.spec.ts
  nexus-sdk-js/src/utils/types.ts
Labels: review

#63 Finish realm
  nexus-sdk-js/src/Realm/__tests__/Realm.spec.ts
  nexus-sdk-js/src/Realm/index.ts
  nexus-sdk-js/src/Realm/types.ts
  nexus-sdk-js/src/Realm/utils.ts
Labels: review

#64 Orgs and Projects events source
  nexus-sdk-js/package-lock.json
  nexus-sdk-js/package.json
  nexus-sdk-js/src/Organization/index.ts
  nexus-sdk-js/src/Organization/types.ts
  nexus-sdk-js/src/Organization/utils.ts
  nexus-sdk-js/src/Project/index.ts
  nexus-sdk-js/src/Project/types.ts
  nexus-sdk-js/src/Project/utils.ts
  nexus-sdk-js/src/utils/events.ts
Labels: review

#57 Update ACL types with v1 final
  nexus-sdk-js/src/ACL.ts
  nexus-sdk-js/src/ACL/__mocks__/mockResponses.ts
  nexus-sdk-js/src/ACL/__tests__/ACL.spec.ts
  nexus-sdk-js/src/ACL/__tests__/__snapshots__/ACL.spec.ts.snap
  nexus-sdk-js/src/ACL/index.ts
  nexus-sdk-js/src/ACL/types.ts
  nexus-sdk-js/src/ACL/utils.ts
  nexus-sdk-js/src/Organization/__tests__/Organization.spec.ts
  nexus-sdk-js/src/Organization/utils.ts
  nexus-sdk-js/src/Project/utils.ts
  nexus-sdk-js/src/Realm/__tests__/Realm.spec.ts
  nexus-sdk-js/src/Realm/utils.ts
  nexus-sdk-js/src/Resource/utils.ts
  nexus-sdk-js/src/View/ElasticSearchView/__tests__/ElasticSearchView.spec.ts
  nexus-sdk-js/src/View/SparqlView/__tests__/SparqlView.spec.ts
  nexus-sdk-js/src/utils/__tests__/index.spec.ts
  nexus-sdk-js/src/utils/index.ts
Labels: review

#65 Update reamdme
  nexus-sdk-js/README.md
Labels: review
